version: '3'

services:
  wpdb:
    image: mysql:${MYSQL_TAG:-8.0}
    volumes:
      - /root/wp/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sqldbpwd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wpdbpwd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psqldbpwd"]
      timeout: 20s
      retries: 10

  wordpress:
    image: wordpress:${WORDPRESS_TAG:-php8.0}
    volumes:
      - /root/wp/wordpress:/var/www/html
    ports:
      - 80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wpdbpwd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3